### PR TITLE
Fixes #129 - lexing superfluous end tags.

### LINKED ISSUE #129: Problem parsing HTML <object> tag
We stumbled upon an issue with parsing HTML <object> tag.
If the <object> tag has enclosed  <param> tags then the closing </object> tag will be placed in the wrong position, possibly due to a wrong parsed tree?

```ruby
$ source = <<-HTML
<object>
  <param></param>
  <param></param>
</object>
HTML
=> "<object>\n  <param></param>\n  <param></param>\n</object>\n"
$ Oga.parse_html(source).to_xml
=> "<object>\n  <param /></object>\n  <param />\n\n"
```

Do you have an idea why it happens? We'll be happy to submit a patch if you can pinpoint the place it happens at.

### PR DESCRIPTION
**Pull request by jakubpawlowicz**
Prevents a superfluous end tag of a self-closing HTML tag from
closing its parent element prematurely, for example:

```html
<object><param></param><param></param></object>
```

(note <param> is self closing) being turned into:

```html
<object><param/></object><param/>
```

### CODE REVIEW

File: lib/oga/xml/lexer.rb [hunk 1]
```diff
@@ -512,8 +512,11 @@ def on_element_end(name = nil)
           end
         end
 
-        add_token(:T_ELEM_END)
+        # Prevents a superfluous end tag of a self-closing HTML tag from
+        # closing its parent element prematurely
+        return if html? and name != nil and name != current_element
```
Comment (YorickPeterse) [inline lib/oga/xml/lexer.rb]: For one liners I prefer the use of `&&` and `||`. It's not a big deal here because precedence doesn't doesn't matter, but I'd prefer to keep it consistent with any other one-liners there might be. For whatever reason I tend to write one-liners where the different precedence of `and` / `or` actually matters, hence I prefer to use `&&` and `||` for them.

Also, the `name != nil` can just be `name` leaving you with:

    return if html? && name && name != current_element

Other than that, great work!

Comment (jakubpawlowicz) [inline lib/oga/xml/lexer.rb]: Sure thing, I'll change the commit!

Comment (YorickPeterse) [inline lib/oga/xml/lexer.rb]: :heart_eyes:

**Comment by jakubpawlowicz** [comment]
This should be it.
